/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ni.edu.uni.programacion.backend.pojo.Vehicle;
import ni.edu.uni.programacion.data.models.ListTableModel;

/**
 *
 * @author Sistemas-05
 */
public class PnlViewVehicle extends javax.swing.JPanel {
      private PnlViewVehicle pnlViewVehicles;    
    private DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form PnlViewVehicle
     */
    public PnlViewVehicle() {
        initComponents();
    }

    public JTable getTblViewVehicle() {
        return tblViewVehicle;
    }

    public JTextField getTxtFinder() {
        return txtFinder;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFinder = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Content = new javax.swing.JScrollPane();
        tblViewVehicle = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Find:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        jPanel1.add(txtFinder, gridBagConstraints);

        btnEliminar.setText("Delete");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        tblViewVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Content.setViewportView(tblViewVehicle);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(Content, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
//        try{
//        int eli = tblViewVehicle.getSelectedRowCount();
//        if(eli>=0){
//            model.removeRow(eli);
//        }else{
//        JOptionPane.showMessageDialog(null, "No hay datos que eliminar");
//               
//           }
//        }catch(HeadlessException ex){
//            JOptionPane.showMessageDialog(null, ex);
//        }      

//          int v = pnlViewVehicles.tblViewVehicle.getSelectionModel().getSelectedItemsCount();
//          
//          if (v >= 0){
//           this.pnlViewVehicles.tblViewVehicle.remove(v);
//          } else {
//              
//              JOptionPane.showMessageDialog(null, "NO hay elementos que borrar");
//          }

               try{
            ListTableModel list  = (ListTableModel)pnlViewVehicles.tblViewVehicle.getModel();
            int selecteRowIndex = pnlViewVehicles.tblViewVehicle.getSelectedRow();
          if(selecteRowIndex >= 0){
            list.removeRow(selecteRowIndex);
          }
          }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Content;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTable tblViewVehicle;
    private javax.swing.JTextField txtFinder;
    // End of variables declaration//GEN-END:variables
}
